In [1]:
import numpy as np

In [2]:
l1 = [1,2,3,4]

In [3]:
n1=np.array(l1)

In [4]:
n1

array([1, 2, 3, 4])

In [5]:
type(n1)

numpy.ndarray

In [6]:
n2=np.array([[1,2,3,4],[4,3,2,1]])

In [7]:
n2

array([[1, 2, 3, 4],
       [4, 3, 2, 1]])

In [8]:
n3=np.zeros((3,4))

In [9]:
n3

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [10]:
n4=np.full((3,4),5)

In [11]:
n4

array([[5, 5, 5, 5],
       [5, 5, 5, 5],
       [5, 5, 5, 5]])

In [12]:
n5=np.arange(10,50,5)

In [13]:
n5

array([10, 15, 20, 25, 30, 35, 40, 45])

In [14]:
n6=np.random.randint(1,100,5)

In [15]:
n6

array([ 5,  7, 51, 59,  6])

In [16]:
n4.shape

(3, 4)

In [17]:
n4.shape=(4,3)

In [18]:
n4

array([[5, 5, 5],
       [5, 5, 5],
       [5, 5, 5],
       [5, 5, 5]])

In [25]:
n7=np.array([10,20,30])
n8=np.array([40,50,60])

In [26]:
np.vstack((n7,n8))

array([[10, 20, 30],
       [40, 50, 60]])

In [21]:
np.hstack((n7,n8))

array([10, 20, 30, 40, 50, 60])

In [22]:
np.column_stack((n7,n8))

array([[10, 40],
       [20, 50],
       [30, 60]])

In [27]:
np.intersect1d(n7,n8)

array([], dtype=int32)

In [29]:
np.setdiff1d(n7,n8)

array([10, 20, 30])

In [30]:
np.setdiff1d(n8,n7)

array([40, 50, 60])

In [31]:
np.sum([n7,n8])

210

In [32]:
np.sum([n7,n8],axis=0)

array([50, 70, 90])

In [33]:
np.sum([n7,n8],axis=1)

array([ 60, 150])

In [34]:
n7=n7+10

In [35]:
n7

array([20, 30, 40])

In [36]:
np.mean(n7)

30.0

In [38]:
n9=np.array([10,20,30])
np.save('my_numpy',n9)

In [39]:
n10=np.load('my_numpy.npy')
n10

array([10, 20, 30])